SHOW DATABASES;

CREATE DATABASE sms;
USE sms;

CREATE TABLE admin(passkey VARCHAR(7) NOT NULL PRIMARY KEY, name VARCHAR(50) NOT NULL, email VARCHAR(30) NOT NULL UNIQUE, username VARCHAR(20) NOT NULL UNIQUE, password VARCHAR(20) NOT NULL);

CREATE TABLE student(name VARCHAR(50), age INT, studentclass VARCHAR(80), city VARCHAR(40));
